name: Deploy Frontend to S3

on:
  push:
    branches:
      - main   # or master, choose your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies
        working-directory: ./front-end
        run: npm ci

      - name: Build and Export Next.js
        working-directory: ./front-end
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./front-end/out s3://${{ secrets.S3_BUCKET }} --delete
